### ISSUE TITLE
Possible to list Chrome extension in the Chrome Web Store?

### ISSUE THREAD

**Issue by gtallen1187** [charlieMonroe/DownieExtensions#2]
@charlieMonroe - first things first, i love this tool you've built.  Thank you!

Is there any particular reason why the Chrome extension can't simply be listed in the Chrome Web Store, similar to what you've done with Firefox?  It seems as though this would be much easier for users than having to go the "Developer -> Load Unpacked" option.  Is this something you might potentially want some help setting up?

-Greg

**Comment by charlieMonroe** [comment]
Hi,

Please go to `Preferences > Browser Extensions` in Downie and click on Chrome - it will bring you to https://blog.charliemonroe.net/downie-and-chrome/ where the situation is explained and steps for a workaround are available.

Please let me know if you have any questions or have trouble installing the workaround.

Cheers,

Charlie Monroe
support@charliemonroe.net
