### ISSUE TITLE
Chrome Extension: Icon for dark mode

### ISSUE THREAD

**Issue by williamukoh** [charlieMonroe/DownieExtensions#3]
The Downie Chrome extension requires a better icon for light and dark modes.

![image](https://user-images.githubusercontent.com/472783/78876459-478e5b80-7a47-11ea-907c-8334dec1aa20.png)

**Comment by charlieMonroe** [comment]
Hi,

Please, in the future, use the in-app support dialog using the Support button in the bottom-right corner of the main window of Downie to report issues. It e.g. includes your macOS version which is a major dealbreaker in this case.

If you are seeing something like this, there's very likely a mismatch between system settings and your Chrome theme. Please note that there are very limited things the extension can do in regards to its appearance and it cannot detect whether a custom theme is light or dark. 

Are you using a custom theme?

Cheers,

Charlie Monroe
support@charliemonroe.net

**Comment by adamwinn** [comment]
Mine was stuck on white and wouldn't go back to the black icon, so I just deleted the `downie_16x16_white.png` image and copied `downie_16x16.png` image and renamed it to `downie_16x16_white.png` so now both images are the dark one

**Comment by charlieMonroe** [comment]
There are plans for this to be an option, but I'm a bit behind due to an accident, so I can't work as fast as I'd like :(
